name: flutter_next_auth
description: Frontend authentication module, integrated with the NextAuth backend; the frontend API is kept consistent with the NextAuth frontend API.
version: 1.0.0
publish_to: none
repository: https://github.com/jcyuan/flutter_next_auth
issue_tracker: https://github.com/jcyuan/flutter_next_auth/issues
homepage: https://github.com/jcyuan/flutter_next_auth#readme
environment:
  sdk: ">=3.10.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  event_bus: ^2.0.0
  flutter_secure_storage: ^10.0.0
